-- Community-scoped access control for B2B portfolio trials and subscriptions.
-- Invite codes are enrollment credentials. Actual authorization is stored per email/user.

ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS platform_role TEXT NOT NULL DEFAULT 'user'
        CHECK (platform_role IN ('user', 'owner')),
    ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.communities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    code_prefix TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'trial'
        CHECK (status IN ('trial', 'poc', 'active', 'suspended', 'ended')),
    max_members INTEGER NOT NULL DEFAULT 100 CHECK (max_members BETWEEN 1 AND 200),
    trial_days INTEGER NOT NULL DEFAULT 14 CHECK (trial_days BETWEEN 1 AND 60),
    access_starts_at TIMESTAMPTZ,
    access_expires_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    purge_after TIMESTAMPTZ,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.community_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    community_id UUID NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
    status TEXT NOT NULL DEFAULT 'invited'
        CHECK (status IN ('invited', 'active', 'revoked', 'expired')),
    access_expires_at TIMESTAMPTZ,
    invited_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    invited_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    joined_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    delete_after TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE (community_id, email),
    UNIQUE (community_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.community_invite_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    community_id UUID NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('admin', 'member')),
    code_value TEXT NOT NULL UNIQUE,
    code_hash TEXT NOT NULL UNIQUE,
    target_email TEXT,
    max_uses INTEGER NOT NULL CHECK (max_uses > 0),
    use_count INTEGER NOT NULL DEFAULT 0 CHECK (use_count >= 0),
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CHECK (kind <> 'admin' OR target_email IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS public.community_admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    community_id UUID REFERENCES public.communities(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_email TEXT,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS community_members_user_idx
    ON public.community_members (user_id, status, access_expires_at);
CREATE INDEX IF NOT EXISTS community_members_community_status_idx
    ON public.community_members (community_id, status, role);
CREATE INDEX IF NOT EXISTS community_invite_codes_lookup_idx
    ON public.community_invite_codes (code_hash, is_active, expires_at);
CREATE INDEX IF NOT EXISTS communities_status_expiry_idx
    ON public.communities (status, access_expires_at);

CREATE OR REPLACE FUNCTION public.touch_community_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS communities_updated_at ON public.communities;
CREATE TRIGGER communities_updated_at
    BEFORE UPDATE ON public.communities
    FOR EACH ROW EXECUTE FUNCTION public.touch_community_updated_at();

DROP TRIGGER IF EXISTS community_members_updated_at ON public.community_members;
CREATE TRIGGER community_members_updated_at
    BEFORE UPDATE ON public.community_members
    FOR EACH ROW EXECUTE FUNCTION public.touch_community_updated_at();

DROP TRIGGER IF EXISTS community_invite_codes_updated_at ON public.community_invite_codes;
CREATE TRIGGER community_invite_codes_updated_at
    BEFORE UPDATE ON public.community_invite_codes
    FOR EACH ROW EXECUTE FUNCTION public.touch_community_updated_at();

CREATE OR REPLACE FUNCTION public.has_active_app_access(check_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
    SELECT
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = check_user_id AND p.platform_role = 'owner'
        )
        OR EXISTS (
            SELECT 1
            FROM public.community_members cm
            JOIN public.communities c ON c.id = cm.community_id
            WHERE cm.user_id = check_user_id
              AND cm.status = 'active'
              AND (cm.access_expires_at IS NULL OR cm.access_expires_at > timezone('utc'::text, now()))
              AND c.status IN ('trial', 'poc', 'active')
              AND (c.access_expires_at IS NULL OR c.access_expires_at > timezone('utc'::text, now()))
        );
$$;

REVOKE ALL ON FUNCTION public.has_active_app_access(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_active_app_access(UUID) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.claim_community_invitation(
    invitation_hash TEXT,
    claiming_user_id UUID,
    claiming_email TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
SET row_security = off
AS $$
DECLARE
    invite public.community_invite_codes%ROWTYPE;
    member public.community_members%ROWTYPE;
    community public.communities%ROWTYPE;
    normalized_email TEXT := lower(trim(claiming_email));
    active_user_count INTEGER;
    active_community_count INTEGER;
    effective_expiry TIMESTAMPTZ;
    is_first_claim BOOLEAN;
BEGIN
    SELECT * INTO invite
    FROM public.community_invite_codes
    WHERE code_hash = invitation_hash
    FOR UPDATE;

    IF invite.id IS NULL OR NOT invite.is_active THEN
        RETURN jsonb_build_object('success', false, 'message', '招待コードは無効です');
    END IF;
    IF invite.expires_at IS NOT NULL AND invite.expires_at <= timezone('utc'::text, now()) THEN
        RETURN jsonb_build_object('success', false, 'message', '招待コードの有効期限が切れています');
    END IF;
    IF invite.use_count >= invite.max_uses THEN
        RETURN jsonb_build_object('success', false, 'message', '招待コードの利用上限に達しています');
    END IF;
    IF invite.kind = 'admin' AND lower(invite.target_email) <> normalized_email THEN
        RETURN jsonb_build_object('success', false, 'message', '指定されたGoogleアカウントと一致しません');
    END IF;

    SELECT * INTO community
    FROM public.communities
    WHERE id = invite.community_id
    FOR UPDATE;

    IF community.id IS NULL OR community.status IN ('suspended', 'ended') THEN
        RETURN jsonb_build_object('success', false, 'message', 'このコミュニティは現在利用できません');
    END IF;

    SELECT * INTO member
    FROM public.community_members
    WHERE community_id = community.id AND email = normalized_email
    FOR UPDATE;

    IF member.id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'このメールアドレスは会員として登録されていません');
    END IF;
    IF member.status = 'revoked' THEN
        RETURN jsonb_build_object('success', false, 'message', 'この会員の利用権限は停止されています');
    END IF;
    IF member.user_id IS NOT NULL AND member.user_id <> claiming_user_id THEN
        RETURN jsonb_build_object('success', false, 'message', 'このメールアドレスは別のGoogleアカウントに登録済みです');
    END IF;
    IF invite.kind = 'admin' AND member.role <> 'admin' THEN
        RETURN jsonb_build_object('success', false, 'message', '代表者用の登録情報が見つかりません');
    END IF;
    IF invite.kind = 'member' AND member.role <> 'member' THEN
        RETURN jsonb_build_object('success', false, 'message', '会員用の登録情報が見つかりません');
    END IF;

    SELECT count(DISTINCT user_id) INTO active_user_count
    FROM public.community_members
    WHERE status = 'active' AND user_id IS NOT NULL;
    IF member.user_id IS NULL AND active_user_count >= 200 THEN
        RETURN jsonb_build_object('success', false, 'message', 'サービス全体の利用上限に達しています');
    END IF;

    SELECT count(*) INTO active_community_count
    FROM public.community_members
    WHERE community_id = community.id AND status = 'active';
    IF member.status <> 'active' AND active_community_count >= community.max_members THEN
        RETURN jsonb_build_object('success', false, 'message', 'コミュニティの利用上限に達しています');
    END IF;

    IF invite.kind = 'admin' AND community.status = 'trial' AND community.access_starts_at IS NULL THEN
        effective_expiry := timezone('utc'::text, now()) + make_interval(days => community.trial_days);
        UPDATE public.communities
        SET access_starts_at = timezone('utc'::text, now()), access_expires_at = effective_expiry
        WHERE id = community.id;
    ELSE
        effective_expiry := COALESCE(member.access_expires_at, community.access_expires_at);
    END IF;

    is_first_claim := member.joined_at IS NULL;
    UPDATE public.community_members
    SET user_id = claiming_user_id,
        status = 'active',
        access_expires_at = effective_expiry,
        joined_at = COALESCE(joined_at, timezone('utc'::text, now())),
        last_seen_at = timezone('utc'::text, now()),
        revoked_at = NULL,
        delete_after = NULL
    WHERE id = member.id;

    IF is_first_claim THEN
        UPDATE public.community_invite_codes
        SET use_count = use_count + 1,
            is_active = CASE WHEN use_count + 1 >= max_uses THEN false ELSE is_active END
        WHERE id = invite.id;
    END IF;

    INSERT INTO public.community_admin_audit_logs
        (actor_user_id, community_id, action, target_email, details)
    VALUES
        (claiming_user_id, community.id, 'invitation_claimed', normalized_email,
         jsonb_build_object('kind', invite.kind));

    RETURN jsonb_build_object(
        'success', true,
        'message', 'コミュニティへの登録が完了しました',
        'community_id', community.id,
        'role', member.role,
        'access_expires_at', effective_expiry
    );
END;
$$;

REVOKE ALL ON FUNCTION public.claim_community_invitation(TEXT, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_community_invitation(TEXT, UUID, TEXT) TO service_role;

-- Purge revoked/expired accounts after the 30-day restoration window. If the same
-- Google user still belongs to another community, only the expired membership is removed.
CREATE OR REPLACE FUNCTION public.purge_expired_community_accounts()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
SET row_security = off
AS $$
DECLARE
    expired_member RECORD;
    deleted_members INTEGER := 0;
    deleted_users INTEGER := 0;
BEGIN
    FOR expired_member IN
        SELECT id, user_id
        FROM public.community_members
        WHERE delete_after IS NOT NULL
          AND delete_after <= timezone('utc'::text, now())
        FOR UPDATE SKIP LOCKED
    LOOP
        DELETE FROM public.community_members WHERE id = expired_member.id;
        deleted_members := deleted_members + 1;

        IF expired_member.user_id IS NOT NULL
           AND NOT EXISTS (
                SELECT 1 FROM public.community_members
                WHERE user_id = expired_member.user_id
           )
           AND NOT EXISTS (
                SELECT 1 FROM public.profiles
                WHERE id = expired_member.user_id AND platform_role = 'owner'
           )
        THEN
            DELETE FROM auth.users WHERE id = expired_member.user_id;
            deleted_users := deleted_users + 1;
        END IF;
    END LOOP;

    DELETE FROM public.communities c
    WHERE c.status = 'ended'
      AND c.purge_after IS NOT NULL
      AND c.purge_after <= timezone('utc'::text, now())
      AND NOT EXISTS (
          SELECT 1 FROM public.community_members cm WHERE cm.community_id = c.id
      );

    RETURN jsonb_build_object(
        'deleted_memberships', deleted_members,
        'deleted_auth_users', deleted_users
    );
END;
$$;

REVOKE ALL ON FUNCTION public.purge_expired_community_accounts() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.purge_expired_community_accounts() TO service_role;

ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_invite_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_admin_audit_logs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.communities FROM anon, authenticated;
REVOKE ALL ON public.community_invite_codes FROM anon, authenticated;
REVOKE ALL ON public.community_admin_audit_logs FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.community_members FROM anon, authenticated;
GRANT SELECT ON public.community_members TO authenticated;

DROP POLICY IF EXISTS "Users can view own community memberships" ON public.community_members;
CREATE POLICY "Users can view own community memberships"
    ON public.community_members FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);

-- Existing user-data RLS is strengthened with the centralized access predicate.
DROP POLICY IF EXISTS "authenticated_read_stocks" ON public.stocks;
CREATE POLICY "authenticated_read_stocks"
    ON public.stocks FOR SELECT TO authenticated
    USING (public.has_active_app_access(auth.uid()));

DROP POLICY IF EXISTS "Users can view own holdings" ON public.holdings;
CREATE POLICY "Users can view own holdings" ON public.holdings FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can insert own holdings" ON public.holdings;
CREATE POLICY "Users can insert own holdings" ON public.holdings FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can update own holdings" ON public.holdings;
CREATE POLICY "Users can update own holdings" ON public.holdings FOR UPDATE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()))
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can delete own holdings" ON public.holdings;
CREATE POLICY "Users can delete own holdings" ON public.holdings FOR DELETE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));

DROP POLICY IF EXISTS "Users can view own portfolio history" ON public.portfolio_history;
CREATE POLICY "Users can view own portfolio history" ON public.portfolio_history FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can create own portfolio history" ON public.portfolio_history;
CREATE POLICY "Users can create own portfolio history" ON public.portfolio_history FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can update own portfolio history" ON public.portfolio_history;
CREATE POLICY "Users can update own portfolio history" ON public.portfolio_history FOR UPDATE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()))
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can delete own portfolio history" ON public.portfolio_history;
CREATE POLICY "Users can delete own portfolio history" ON public.portfolio_history FOR DELETE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));

DROP POLICY IF EXISTS "Users can view own dividend import batches" ON public.dividend_import_batches;
CREATE POLICY "Users can view own dividend import batches" ON public.dividend_import_batches FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can create own dividend import batches" ON public.dividend_import_batches;
CREATE POLICY "Users can create own dividend import batches" ON public.dividend_import_batches FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can delete own dividend import batches" ON public.dividend_import_batches;
CREATE POLICY "Users can delete own dividend import batches" ON public.dividend_import_batches FOR DELETE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));

DROP POLICY IF EXISTS "Users can view own dividend payments" ON public.dividend_payments;
CREATE POLICY "Users can view own dividend payments" ON public.dividend_payments FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can create own dividend payments" ON public.dividend_payments;
CREATE POLICY "Users can create own dividend payments" ON public.dividend_payments FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can update own dividend payments" ON public.dividend_payments;
CREATE POLICY "Users can update own dividend payments" ON public.dividend_payments FOR UPDATE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()))
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can delete own dividend payments" ON public.dividend_payments;
CREATE POLICY "Users can delete own dividend payments" ON public.dividend_payments FOR DELETE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));

DROP POLICY IF EXISTS "Users can view own expense items" ON public.expense_items;
CREATE POLICY "Users can view own expense items" ON public.expense_items FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can create own expense items" ON public.expense_items;
CREATE POLICY "Users can create own expense items" ON public.expense_items FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can update own expense items" ON public.expense_items;
CREATE POLICY "Users can update own expense items" ON public.expense_items FOR UPDATE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()))
    WITH CHECK (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));
DROP POLICY IF EXISTS "Users can delete own expense items" ON public.expense_items;
CREATE POLICY "Users can delete own expense items" ON public.expense_items FOR DELETE TO authenticated
    USING (auth.uid() = user_id AND public.has_active_app_access(auth.uid()));

COMMENT ON TABLE public.community_members IS
    'Email allowlist and authorization state. Portfolio data is never exposed through this table.';
COMMENT ON COLUMN public.community_invite_codes.code_value IS
    'Server-only rotatable enrollment credential. Direct client access is revoked.';
